name: Tach Check

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  tach-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tach==0.6.9

    - name: Run Tach
      run: tach check