name: Daily Price Update and Publish

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-prices:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Git config
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install build semver twine
        
    - name: Update prices
      run: python update_prices.py
      
    - name: Check for changes
      id: git-check
      run: |
        git status --porcelain
        echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Bump package version
      if: steps.git-check.outputs.changed > 0
      id: bump-version
      run: |
        # Call the bump_version.py script
        NEW_VERSION=$(python bump_version.py patch | tail -n 1)
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        
    - name: Commit and push changes
      if: steps.git-check.outputs.changed > 0
      run: |
        git add .
        git commit -m "chore: Update token prices (${{ steps.date.outputs.date }})"
        git push origin HEAD:main
        
    - name: Create Release
      if: steps.git-check.outputs.changed > 0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v${{ steps.bump-version.outputs.new_version }} \
          --title "Release v${{ steps.bump-version.outputs.new_version }}" \
          --notes "Automated release for price updates on ${{ steps.date.outputs.date }}\n\nThis release contains updated token prices from the latest API data." \
          --generate-notes
        
    - name: Build package
      if: steps.git-check.outputs.changed > 0
      run: python -m build
      
    - name: Check built distributions
      if: steps.git-check.outputs.changed > 0
      run: |
        python -m pip install --upgrade twine
        twine check dist/*
        ls -la dist/
    
    - name: Upload dists to GitHub Release
      if: steps.git-check.outputs.changed > 0
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/*
        tag_name: v${{ steps.bump-version.outputs.new_version }}
        name: Release v${{ steps.bump-version.outputs.new_version }}
        body: |
          Automated release for price updates on ${{ steps.date.outputs.date }}
          This release contains updated token prices from the latest API data.
          
    - name: Publish package to PyPI
      if: steps.git-check.outputs.changed > 0
      uses: pypa/gh-action-pypi-publish@release/v1
      # password input removed for trusted publishing
